CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  done BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE todos_test (
  id SERIAL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  done BOOLEAN DEFAULT false NOT NULL
)
